/**
 * Plan Mode 计划文件模板
 *
 * 提供标准化的计划文件结构
 */

export interface PlanTemplateData {
  objective: string
  keyFiles: Array<{
    path: string
    description: string
  }>
  steps: Array<{
    name: string
    file: string
    action: string
    rationale: string
  }>
  verification: string
  notes?: string
}

/**
 * 生成计划文件内容
 */
export function generatePlanFile(data: PlanTemplateData): string {
  const { objective, keyFiles, steps, verification, notes } = data

  const keyFilesSection = keyFiles
    .map((f) => `- \`${f.path}\` - ${f.description}`)
    .join("\n")

  const stepsSection = steps
    .map(
      (step, index) => `
### ${index + 1}. ${step.name}

- **File**: \`${step.file}\`
- **Action**: ${step.action}
- **Rationale**: ${step.rationale}
`
    )
    .join("\n")

  const notesSection = notes
    ? `
## Notes

${notes}
`
    : ""

  return `# Implementation Plan

## Objective

${objective}

## Key Files & Context

${keyFilesSection}

## Implementation Steps

${stepsSection}

## Verification & Testing

${verification}
${notesSection}

---

*Generated by Lite OpenCode Plan Mode*
`
}

/**
 * 空计划模板（用于初始化）
 */
export function getEmptyPlanTemplate(): string {
  return `# Implementation Plan

## Objective

<!-- Describe what this plan will achieve -->

## Key Files & Context

<!-- List files that will be modified -->
- \`path/to/file.ts\` - Description of what this file does

## Implementation Steps

### 1. Step Name

- **File**: \`path/to/file.ts\`
- **Action**: Specific description of changes
- **Rationale**: Why this approach

## Verification & Testing

<!-- How to verify the changes work correctly -->

## Notes

<!-- Important context, gotchas, or dependencies -->
`
}

/**
 * 解析计划文件（简单解析）
 */
export function parsePlanFile(content: string): Partial<PlanTemplateData> {
  const data: Partial<PlanTemplateData> = {}

  // 提取 Objective
  const objectiveMatch = content.match(/## Objective\n\n([^#]+)/)
  if (objectiveMatch) {
    data.objective = objectiveMatch[1].trim()
  }

  // 提取 Key Files
  const keyFilesMatch = content.match(/## Key Files[\s\S]*?\n\n([^#]+)/)
  if (keyFilesMatch) {
    const lines = keyFilesMatch[1].trim().split("\n")
    data.keyFiles = lines
      .map((line) => {
        const match = line.match(/- \`([^`]+)\` - (.+)/)
        if (match) {
          return {
            path: match[1],
            description: match[2],
          }
        }
        return null
      })
      .filter(Boolean) as Array<{ path: string; description: string }>
  }

  // 提取 Verification
  const verificationMatch = content.match(/## Verification[\s\S]*?\n\n([^#]+)/)
  if (verificationMatch) {
    data.verification = verificationMatch[1].trim()
  }

  // 提取 Notes
  const notesMatch = content.match(/## Notes\n\n([^]+)/)
  if (notesMatch) {
    data.notes = notesMatch[1].trim()
  }

  return data
}
